-- ==========================================================================
-- ManakAi / ManakMitra — Phase 2: BIS knowledge provenance + search readiness
-- Safe additive migration. Existing rows are preserved.
--
-- Knowledge classification:
--   official_verified  = information verified against an authoritative source
--   demonstration_mock = synthetic/demo information; never present as official
--   application_generated = generated by this application; not an external source
--
-- This migration prepares the schema for keyword/full-text retrieval. Vector
-- search is intentionally NOT enabled in Phase 2.
-- ==========================================================================

-- ---------------------------------------------------------------------------
-- Reusable provenance fields
-- ---------------------------------------------------------------------------
alter table public.standards
  add column if not exists knowledge_status text not null default 'official_verified'
    check (knowledge_status in ('official_verified', 'demonstration_mock', 'application_generated')),
  add column if not exists source text,
  add column if not exists source_url text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

alter table public.services
  add column if not exists knowledge_status text not null default 'official_verified'
    check (knowledge_status in ('official_verified', 'demonstration_mock', 'application_generated')),
  add column if not exists source text,
  add column if not exists source_url text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

alter table public.faqs
  add column if not exists knowledge_status text not null default 'official_verified'
    check (knowledge_status in ('official_verified', 'demonstration_mock', 'application_generated')),
  add column if not exists source text,
  add column if not exists source_url text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

alter table public.labs
  add column if not exists knowledge_status text not null default 'official_verified'
    check (knowledge_status in ('official_verified', 'demonstration_mock', 'application_generated')),
  add column if not exists source text,
  add column if not exists source_url text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

alter table public.cert_steps
  add column if not exists knowledge_status text not null default 'official_verified'
    check (knowledge_status in ('official_verified', 'demonstration_mock', 'application_generated')),
  add column if not exists source text,
  add column if not exists source_url text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

alter table public.licenses
  add column if not exists knowledge_status text not null default 'demonstration_mock'
    check (knowledge_status in ('official_verified', 'demonstration_mock', 'application_generated')),
  add column if not exists source text,
  add column if not exists source_url text,
  add column if not exists source_updated_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

-- ---------------------------------------------------------------------------
-- Classify the existing seed explicitly.
-- Standards/services/FAQs/labs/certification steps are the project's
-- curated BIS/public-information seed. License rows are explicitly synthetic.
-- ---------------------------------------------------------------------------
update public.standards
set knowledge_status = 'official_verified',
    source = coalesce(source, 'BIS public standards metadata / Know Your Standards'),
    source_url = coalesce(source_url, 'https://www.services.bis.gov.in/'),
    updated_at = now()
where knowledge_status = 'official_verified' and source is null;

update public.services
set knowledge_status = 'official_verified',
    source = coalesce(source, 'BIS public information used for the ManakMitra curated seed'),
    source_url = coalesce(source_url, 'https://www.bis.gov.in/'),
    updated_at = now()
where knowledge_status = 'official_verified' and source is null;

update public.faqs
set knowledge_status = 'official_verified',
    source = coalesce(source, 'BIS public information used for the ManakMitra curated seed'),
    source_url = coalesce(source_url, 'https://www.bis.gov.in/'),
    updated_at = now()
where knowledge_status = 'official_verified' and source is null;

update public.labs
set knowledge_status = 'official_verified',
    source = coalesce(source, 'BIS public information used for the ManakMitra curated seed'),
    source_url = coalesce(source_url, 'https://www.bis.gov.in/'),
    updated_at = now()
where knowledge_status = 'official_verified' and source is null;

update public.cert_steps
set knowledge_status = 'official_verified',
    source = coalesce(source, 'BIS public information used for the ManakMitra curated seed'),
    source_url = coalesce(source_url, 'https://www.bis.gov.in/'),
    updated_at = now()
where knowledge_status = 'official_verified' and source is null;

update public.licenses
set knowledge_status = 'demonstration_mock',
    source = coalesce(source, 'ManakMitra demonstration seed — fictional license records'),
    source_url = null,
    updated_at = now();

-- ---------------------------------------------------------------------------
-- Search preparation
-- ---------------------------------------------------------------------------
create index if not exists idx_standards_is_number on public.standards(is_number);
create index if not exists idx_standards_category_status on public.standards(category, status);
create index if not exists idx_standards_knowledge_status on public.standards(knowledge_status);
create index if not exists idx_standards_source on public.standards(source);

-- Keep the existing GIN expression index and add a named full-text vector
-- column for predictable future retrieval. No embeddings/vector extension.
alter table public.standards
  add column if not exists search_vector tsvector
  generated always as (
    to_tsvector(
      'english',
      coalesce(is_number, '') || ' ' ||
      coalesce(title, '') || ' ' ||
      coalesce(description, '') || ' ' ||
      coalesce(category, '') || ' ' ||
      coalesce(dept, '')
    )
  ) stored;

create index if not exists idx_standards_search_vector
  on public.standards using gin(search_vector);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------
create or replace function public.set_knowledge_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_standards_updated_at on public.standards;
create trigger trg_standards_updated_at
before update on public.standards
for each row execute function public.set_knowledge_updated_at();

drop trigger if exists trg_services_updated_at on public.services;
create trigger trg_services_updated_at
before update on public.services
for each row execute function public.set_knowledge_updated_at();

drop trigger if exists trg_faqs_updated_at on public.faqs;
create trigger trg_faqs_updated_at
before update on public.faqs
for each row execute function public.set_knowledge_updated_at();

drop trigger if exists trg_labs_updated_at on public.labs;
create trigger trg_labs_updated_at
before update on public.labs
for each row execute function public.set_knowledge_updated_at();

drop trigger if exists trg_cert_steps_updated_at on public.cert_steps;
create trigger trg_cert_steps_updated_at
before update on public.cert_steps
for each row execute function public.set_knowledge_updated_at();

drop trigger if exists trg_licenses_updated_at on public.licenses;
create trigger trg_licenses_updated_at
before update on public.licenses
for each row execute function public.set_knowledge_updated_at();

-- ---------------------------------------------------------------------------
-- Provenance indexes for the remaining knowledge tables
-- ---------------------------------------------------------------------------
create index if not exists idx_services_knowledge_status on public.services(knowledge_status);
create index if not exists idx_faqs_category on public.faqs(category);
create index if not exists idx_faqs_knowledge_status on public.faqs(knowledge_status);
create index if not exists idx_labs_knowledge_status on public.labs(knowledge_status);
create index if not exists idx_cert_steps_knowledge_status on public.cert_steps(knowledge_status);
create index if not exists idx_licenses_knowledge_status on public.licenses(knowledge_status);
